apiVersion: v1
kind: ConfigMap
metadata:
  name: wanderlust-config
  namespace: wanderlust
  labels:
    app.kubernetes.io/name: wanderlust
data:
  NODE_ENV: "production"
  PORT: "8080"
  MONGODB_HOST: "mongodb-service"
  MONGODB_PORT: "27017"
